openapi: 3.0.3
info:
  title: Smart-EVSE V3
  version: 1.0.0
servers:
  - url: 'http://localhost'
    description: 'Example Server'
paths:
  /settings:
    get:
      operationId: getSettings
      tags:
        - Operations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nullable'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  debug: 
                    type: string
                    example: ""
                  mode: 
                    description: |-
                      <b>0_OFF <br />
                      <b>1_NORMAL <br />
                      <b>2_SOLAR <br />
                      <b>3_SMART
                    type: string
                    example: "2_SOLAR"
                  access: 
                    type: integer
                    minimum: 0
                    maximum: 1
                  evse_mode: 
                    type: integer
                  charge_current: 
                    type: integer
                  current_min: 
                    type: integer
                  current_max: 
                    type: integer
                  current_main: 
                    type: integer
                  solar_max_import: 
                    type: integer
                  solar_start_current: 
                    type: integer
                  solar_stop_time: 
                    type: integer
                  temp: 
                    type: integer
                  battery_current: 
                    type: integer
                  battery_last_update: 
                    type: integer
                    example: 1647798299
                  backlight_timer: 
                    type: integer
                  backlight_status: 
                    type: string
                    example: "ON"
                  L1: 
                    type: integer
                  L2: 
                    type: integer
                  L3: 
                    type: integer
    post:
      operationId: updateSettings
      tags:
        - Operations
      parameters:
        - in: path
          name: mode
          description: |-
            Only following values are permitted: <br />
              <b>0</b>: OFF <br />
              <b>1</b>: NORMAL <br />
              <b>2</b>: SOLAR <br />
              <b>3</b>: SMART
          required: false
          schema:
            type: integer
        - in: path
          name: max_current
          description: |-
            Only applicable if <b>mode == 1</b> (NORMAL) <br />
            Desired current multiplied by 10 <br />
            <br />
            Examples: <br />
            If the desired current is <b>8.3A</b> the value to be send is <b>83</b> <br />
            If the desired current is <b>6A</b> the value to be send is <b>60</b>
          required: false
          schema:
            type: integer
        - in: path
          name: battery_current
          description: |-
            Actual home battery current multiplied by 10 <br />
            A <b>positive</b> number means the home battery is <b>charging</b> <br />
            A <b>negative</b> number means the home battery is<b> discharging</b> <br />
          required: false
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nullable'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  result: 
                    type: string
components:
  schemas:
    Nullable:
      type: object
      nullable: true